export interface Palette {
  name: string;
  img: string;
  active: boolean;
  colors: string[];
}

export const palettes: Palette[] = [
  
  {
    name: "Arcade Floor",
    img: "#",
    active: true,
    colors: ["Black", "Blacklight"],
  },
  {
    name: "Aurora Horealis",
    img: "#",
    active: true,
    colors: ["Green", "Rainbow"],
  },
  {
    name: "Baby Sparkles",
    img: "#",
    active: true,
    colors: ["Pink"],
  },
   {
    name: "Bae Mitzvah",
    img: "#",
    active: true,
    colors: ["Pink", "Iridescent","Jewish"],
  },
  {
    name: "Bar Fly",
    img: "#",
    active: true,
    colors: ["Iridescent", "Pink", "Green"],
  },
  {
    name: "Bar Fly Flakes",
    img: "#",
    active: true,
    colors: ["Iridescent", "Pink", "Green", "Flakes"],
  },
  {
    name: "Bar Fly Micro",
    img: "#",
    active: true,
    colors: ["Iridescent", "Pink", "Green", "Micro"],
  },
  {
    name: "Bejeweled",
    img: "#",
    active: true,
    colors: ["Rainbow", "Blue","Purple"],
  },
  {
    name: "Bling Bling",
    img: "#",
    active: true,
    colors: ["Gold"],
  },
  {
    name: "Bling Bling Flakes",
    img: "#",
    active: true,
    colors: ["Gold", "Flakes"],
  },
  {
    name: "Bling Bling Micro",
    img: "#",
    active: true,
    colors: ["Gold", "Micro"],
  },
  {
    name: "Blue Fly Skies",
    img: "#",
    active: true,
    colors: ["Blue"],
  },
   {
    name: "Blue Fly Skies Micro",
    img: "#",
    active: true,
    colors: ["Blue","Micro"],
  },
  {
    name: "Bratty",
    img: "#",
    active: true,
    colors: ["Blue", "Iridescent"],
  },
  {
    name: "Bubblegum Bae",
    img: "#",
    active: true,
    colors: ["Pink", "Blacklight"],
  },
  {
    name: "Bubblegum Bae Flakes",
    img: "#",
    active: true,
    colors: ["Pink", "Blacklight", "Flakes"],
  },
  {
    name: "Bubblegum Bae Micro",
    img: "#",
    active: true,
    colors: ["Pink", "Blacklight", "Micro"],
  },
  {
    name: "Bye Bye Binary",
    img: "#",
    active: true,
    colors: ["Purple", "Green"],
  },
  {
    name: "C U Later",
    img: "#",
    active: true,
    colors: ["Orange", "Copper"],
  },
  {
    name: "C U Later Flakes",
    img: "#",
    active: true,
    colors: ["Orange", "Copper", "Flakes"],
  },
  {
    name: "C U Later Micro",
    img: "#",
    active: true,
    colors: ["Orange", "Copper", "Micro"],
  },
  {
    name: "Call Me Big Papaya",
    img: "#",
    active: true,
    colors: ["Orange", "Blacklight"],
  },
  {
    name: "Call You Mine",
    img: "#",
    active: true,
    colors: ["Pink", "Blacklight"],
  },
  {
    name: "Carolina Bae",
    img: "#",
    active: true,
    colors: ["Blue", "Blacklight"],
  },
  {
    name: "Carolina Bae Micro",
    img: "#",
    active: true,
    colors: ["Blue", "Blacklight", "Micro"],
  },
  {
    name: "Celeste and Stars",
    img: "#",
    active: true,
    colors: ["Silver", "Iridescent"],
  },
  {
    name: "Challah Back Girl",
    img: "#",
    active: true,
    colors: ["Blue", "Jewish"],
  },
  {
    name: "Champagne Flakes",
    img: "#",
    active: true,
    colors: ["Gold", "Flakes"],
  },
  {
    name: "Champagne Kisses",
    img: "#",
    active: true,
    colors: ["Gold", "Green", "Iridescent"],
  },
  {
    name: "Chip This",
    img: "#",
    active: true,
    colors: ["Brown"],
  },
  {
    name: "Citrus Ice",
    img: "#",
    active: true,
    colors: ["Yellow","Blacklight"],
  },
  {
    name: "Civic Duty",
    img: "#",
    active: true,
    colors: ["Blue", "Silver"],
  },
  {
    name: "Cloud 9",
    img: "#",
    active: true,
    colors: ["White", "Iridescent", "Blacklight"],
  },
  
  {
    name: "Day Break Flakes",
    img: "#",
    active: true,
    colors: ["Iridescent", "Blue", "Orange", "Flakes"],
  },
  {
    name: "Day Break",
    img: "#",
    active: true,
    colors: ["Iridescent", "Blue", "Orange"],
  },
  {
    name: "Day Break Micro",
    img: "#",
    active: true,
    colors: ["Iridescent", "Blue", "Orange", "Micro"],
  },
  {
    name: "Disco Pants",
    img: "#",
    active: true,
    colors: ["Pink", "Purple", "Gold"],
  },
  {
    name: "Disco Pants Micro",
    img: "#",
    active: true,
    colors: ["Pink", "Purple", "Gold","Micro"],
  },
  {
    name: "Disco Queen",
    img: "#",
    active: true,
    colors: ["Gold", "Iridescent"],
  },
  {
    name: "Dorothy's Red Bottoms",
    img: "#",
    active: true,
    colors: ["Red"],
  },
  {
    name: "Dorothy's Red Bottoms Micro",
    img: "#",
    active: true,
    colors: ["Red", "Micro"],
  },
  {
    name: "Dorothy's Red Flakes",
    img: "#",
    active: true,
    colors: ["Red", "Flakes"],
  },
  {
    name: "Due Tee",
    img: "#",
    active: true,
    colors: ["Brown"],
  },
  {
    name: "Electric Clementine Flakes",
    img: "#",
    active: true,
    colors: ["Orange", "Blacklight", "Flakes"],
  },
  {
    name: "Electric Clementine Micro",
    img: "#",
    active: true,
    colors: ["Orange", "Blacklight", "Micro"],
  },
  {
    name: "Electric Clementine",
    img: "#",
    active: true,
    colors: ["Orange", "Blacklight"],
  },
  {
    name: "Electric Slipper Flakes",
    img: "#",
    active: true,
    colors: ["Blue", "Iridescent", "Flakes"],
  },
  {
    name: "Emerald City Skyline",
    img: "#",
    active: true,
    colors: ["Green"],
  },
  {
    name: "Emerald City Flakes",
    img: "#",
    active: true,
    colors: ["Green", "Flakes"],
  },
   {
    name: "Emerald City Micro",
    img: "#",
    active: true,
    colors: ["Green", "Micro"],
  },
  {
    name: "Enchantress",
    img: "#",
    active: true,
    colors: ["Red", "Pink"],
  },
  {
    name: "Enchantress Micro",
    img: "#",
    active: true,
    colors: ["Red", "Pink", "Micro"],
  },
  {
    name: "Erase Her Flakes",
    img: "#",
    active: true,
    colors: ["Pink", "Flakes"],
  },
  {
    name: "Face Frosting",
    img: "#",
    active: true,
    colors: ["Iridescent", "Rainbow"],
  },
  {
    name: "Facefetti",
    img: "#",
    active: true,
    colors: ["Yellow", "Rainbow"],
  },
  {
    name: "Facefetti Micro",
    img: "#",
    active: true,
    colors: ["Yellow", "Rainbow","Micro"],
  },
  {
    name: "Flower Child",
    img: "#",
    active: true,
    colors: ["Pink", "Rainbow", "Blacklight"],
  },
  {
    name: "Frickin' Bats",
    img: "#",
    active: true,
    colors: ["Black", "Halloween"],
  },
  {
    name: "Friend In Me",
    img: "#",
    active: true,
    colors: ["Blue","Blacklight"],
  },
  {
    name: "Full Moon",
    img: "#",
    active: true,
    colors: ["Iridescent", "Rainbow"],
  },
  {
    name: "Full Moon Flakes",
    img: "#",
    active: true,
    colors: ["Iridescent", "Rainbow", "Flakes"],
  },
   {
    name: "Full Moon Micro",
    img: "#",
    active: true,
    colors: ["Iridescent", "Rainbow", "Micro"],
  },
  {
    name: "Glazed and Confused",
    img: "#",
    active: true,
    colors: ["Green", "Purple", "420"],
  },
  {
    name: "Good For You",
    img: "#",
    active: true,
    colors: ["Iridescent", "Orange", "Blue"],
  },
  {
    name: "Green Goddess",
    img: "#",
    active: true,
    colors: ["Green", "Rainbow"],
  },
  {
    name: "Hot Dog Real Bad",
    img: "#",
    active: true,
    colors: ["Red", "Blue"],
  },
  {
    name: "Hot Tamale",
    img: "#",
    active: true,
    colors: ["Orange", "Yellow", "Blacklight"],
  },
  {
    name: "Incantation",
    img: "#",
    active: true,
    colors: ["Purple"],
  },
  {
    name: "It Girl",
    img: "#",
    active: true,
    colors: ["Iridescent", "Green"],
  },
  {
    name: "Jay Walker",
    img: "#",
    active: true,
    colors: ["Pink", "Iridescent"],
  },
  {
    name: "Jay Walker Micro",
    img: "#",
    active: true,
    colors: ["Pink", "Iridescent","Micro"],
  },
  {
    name: "Lavender Bae",
    img: "#",
    active: true,
    colors: ["Purple","Blacklight"],
  },
  {
    name: "Lavender Bae Micro",
    img: "#",
    active: true,
    colors: ["Purple","Blacklight","Micro"],
  },
  {
    name: "Lick the Spoon",
    img: "#",
    active: true,
    colors: ["Silver", "Rainbow", "Iridescent"],
  },
  {
    name: "Light Catcher",
    img: "#",
    active: true,
    colors: ["Yellow", "Purple", "Iridescent"],
  },
  {
    name: "Light Catcher Flakes",
    img: "#",
    active: true,
    colors: ["Yellow", "Purple", "Iridescent", "Flakes"],
  },
  {
    name: "Light Catcher Micro",
    img: "#",
    active: true,
    colors: ["Yellow", "Purple", "Iridescent", "Micro"],
  },
  {
    name: "Lights Out",
    img: "#",
    active: true,
    colors: ["Black", "Gold"],
  },
  {
    name: "Lights Out Micro",
    img: "#",
    active: true,
    colors: ["Black", "Gold","Micro"],
  },
  {
    name: "Lilac Dreams",
    img: "#",
    active: true,
    colors: ["Purple"],
  },
  {
    name: "Love Always",
    img: "#",
    active: true,
    colors: ["Rainbow"],
  },
  {
    name: "Love Both Ways",
    img: "#",
    active: true,
    colors: ["Pink", "Blue"],
  },
  {
    name: "Love Yourself",
    img: "#",
    active: true,
    colors: ["Purple"],
  },
  {
    name: "Lunar Magic Flakes",
    img: "#",
    active: true,
    colors: ["Blue", "Flakes"],
  },
  {
    name: "Lunar Magick",
    img: "#",
    active: true,
    colors: ["Blue"],
  },
  {
    name: "Mama Sparkles Magick",
    img: "#",
    active: true,
    colors: ["Purple", "Blue", "Iridescent"],
  },
  {
    name: "Matcha Mint Chip",
    img: "#",
    active: true,
    colors: ["Green", "Blacklight", "Iridescent"],
  },
  {
    name: "Matcha Mint Flakes",
    img: "#",
    active: true,
    colors: ["Green", "Iridescent", "Blacklight", "Flakes"],
  },
   {
    name: "Matcha Mint Micro",
    img: "#",
    active: true,
    colors: ["Green", "Iridescent", "Blacklight", "Micro"],
  },
  {
    name: "Mellow Yellow",
    img: "#",
    active: true,
    colors: ["Yellow", "Rainbow", "Blacklight", "420"],
  },
  {
    name: "Mermaid Vibes",
    img: "#",
    active: true,
    colors: ["Blue", "Green", "Purple"],
  },
  {
    name: "Mermaid Vibes Micro",
    img: "#",
    active: true,
    colors: ["Blue", "Green", "Purple","Micro"],
  },
  {
    name: "Mirror Mirror",
    img: "#",
    active: true,
    colors: ["Silver"],
  },
   {
    name: "Mirror Mirror Micro",
    img: "#",
    active: true,
    colors: ["Silver","Micro"],
  },
   {
    name: "Moon Child",
    img: "#",
    active: true,
    colors: ["Iridescent","Rainbow"],
  },
  {
    name: "Nebula",
    img: "#",
    active: true,
    colors: ["Blue", "Black", "Green", "Purple"],
  },
  {
    name: "Nightfall",
    img: "#",
    active: true,
    colors: ["Black"],
  },
   {
    name: "Nightfall Micro",
    img: "#",
    active: true,
    colors: ["Black","Micro"],
  },
  
  {
    name: "Oh Snap",
    img: "#",
    active: true,
    colors: ["Black", "Silver"],
  },
  {
    name: "Paint the Mouse",
    img: "#",
    active: true,
    colors: ["Siver", "Blacklight"],
  },
  {
    name: "Party Foul Flakes",
    img: "#",
    active: true,
    colors: ["Rainbow", "Flakes"],
  },
  {
    name: "Piano Bar Slut",
    img: "#",
    active: true,
    colors: ["Pink"],
  },
 
  {
    name: "Pixie",
    img: "#",
    active: true,
    colors: ["White", "Pink", "Blacklight"],
  },
  {
    name: "Pumpkin Spice Vibes",
    img: "#",
    active: true,
    colors: ["Red", "Orange", "Yellow", "Gold"],
  },
  {
    name: "Rave Candy",
    img: "#",
    active: true,
    colors: ["Purple", "Blacklight"],
  },
  {
    name: "Reef Her Flakes",
    img: "#",
    active: true,
    colors: ["Pink", "Flakes"],
  },
  {
    name: "Reign On Me",
    img: "#",
    active: true,
    colors: ["Purple"],
  },
  {
    name: "Reign On Me Flakes",
    img: "#",
    active: true,
    colors: ["Purple", "Flakes"],
  },
  {
    name: "Reign On Me Micro",
    img: "#",
    active: true,
    colors: ["Purple", "Micro"],
  },
  {
    name: "Roller Rink",
    img: "#",
    active: true,
    colors: ["Pink", "Rainbow", "Blacklight"],
  },
  {
    name: "Sneaky Link",
    img: "#",
    active: true,
    colors: ["Green", "Gold"],
  },
  {
    name: "Solstice Vibes",
    img: "#",
    active: true,
    colors: ["Gold", "Silver"],
  },
  {
    name: "Sparkle Kingdom",
    img: "#",
    active: true,
    colors: ["Gold", "Blacklight"],
  },
  {
    name: "Spellbound",
    img: "#",
    active: true,
    colors: ["Purple", "Blacklight"],
  },
  {
    name: "Spellbound Flakes",
    img: "#",
    active: true,
    colors: ["Purple", "Blacklight", "Flakes"],
  },
  {
    name: "Starbright",
    img: "#",
    active: true,
    colors: ["Silver"],
  },
  {
    name: "Starbright Flakes",
    img: "#",
    active: true,
    colors: ["Silver", "Flakes"],
  },
  {
    name: "Starbright Micro",
    img: "#",
    active: true,
    colors: ["Silver", "Micro"],
  },
  {
    name: "Stormy Vibes",
    img: "#",
    active: true,
    colors: ["Black", "Purple"],
  },
  {
    name: "Stormy Vibes Flakes",
    img: "#",
    active: true,
    colors: ["Black", "Flakes"],
  },
  {
    name: "Sunshine Bae",
    img: "#",
    active: true,
    colors: ["Yellow", "Blacklight"],
  },
   {
    name: "Sunshine Bae Micro",
    img: "#",
    active: true,
    colors: ["Yellow", "Blacklight","Micro"],
  },
  {
    name: "Sunshine Ice Flakes",
    img: "#",
    active: true,
    colors: ["Yellow", "Blacklight", "Flakes"],
  },
  {
    name: "Sweet Dreamz",
    img: "#",
    active: true,
    colors: ["Bue"],
  },
  {
    name: "Sweet Hearts",
    img: "#",
    active: true,
    colors: ["Iridescent"],
  },
  {
    name: "Tainted Heart",
    img: "#",
    active: true,
    colors: ["Iridescent", "Pink", "Green"],
  },
  {
    name: "Tastes Like Pink",
    img: "#",
    active: true,
    colors: ["Pink", "Gold"],
  },
  {
    name: "TechnoScope",
    img: "#",
    active: true,
    colors: ["Silver", "Iridescent", "Blacklight"],
  },
  
  {
    name: "Touch Grass",
    img: "#",
    active: true,
    colors: ["Green"],
  },
  {
    name: "Twinkle Twinkle",
    img: "#",
    active: true,
    colors: ["Pink", "Iridescent"],
  },
  {
    name: "Undercover Princess Flakes",
    img: "#",
    active: true,
    colors: ["Purple", "Pink", "Silver", "Flakes"],
  },
  {
    name: "Vineyard Ice",
    img: "#",
    active: true,
    colors: ["Purple", "Iridescent"],
  },
  {
    name: "Viva La Zebra!",
    img: "#",
    active: true,
    colors: ["Black", "White"],
  },
  {
    name: "Wanna Play?",
    img: "#",
    active: true,
    colors: ["Red", "Green", "Silver", "Halloween"],
  },
  {
    name: "We Got Spirit",
    img: "#",
    active: true,
    colors: ["Red", "Silver"],
  },
  {
    name: "Water Country Flakes",
    img: "#",
    active: true,
    colors: ["Blue", "Flakes"],
  },
  {
    name: "Wine About It",
    img: "#",
    active: true,
    colors: ["Red"],
  },
   {
    name: "Wedding Cake",
    img: "#",
    active: true,
    colors: ["Gold","Pink","Yellow","Iridescent"],
  },
  {
    name: "Y2J",
    img: "#",
    active: true,
    colors: ["Pink", "Iridescent"],
  },
  {
    name: "Yellow Brick Hoe",
    img: "#",
    active: true,
    colors: ["Yellow", "Gold"],
  },
];

export const activePalettes = palettes.filter((p) => !!p.active);

const uniqueColors = palettes.reduce((acc, p) => {
  p.colors.forEach((color) => {
    acc.add(color);
  });

  return acc;
}, new Set<string>());

export const colorFilters = Array.from(uniqueColors);
