
on:
  workflow_dispatch:
  push:
    branches:
     - preview
     - production
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Set environment for branch
        run: |
          if [[ $GITHUB_REF == 'refs/heads/preview' ]]; then
              echo "GCP_BUCKET_NAME=ddc_dev_scripts" >> "$GITHUB_ENV"
          else
              echo "GCP_BUCKET_NAME=ddc_dev_scripts" >> "$GITHUB_ENV"
          fi
          
      - name: Authenticate on GCS
        uses: google-github-actions/auth@v0
        with:
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}'
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'
          
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        
      - name: install dependencies
        run: npm install
        
      - name: build application
        run: npm run build
        
      - name: push to gcp bucket
        run: gcloud storage cp ./dist/assets/index.js gs://"${{ env.GCP_BUCKET_NAME }}"
        
